if(NOT DEFINED BUNDLE_DIR OR NOT IS_DIRECTORY "${BUNDLE_DIR}")
  message(FATAL_ERROR "BUNDLE_DIR must point to an existing .app directory")
endif()

set(MLT_MODULE_DIR "${BUNDLE_DIR}/Contents/Resources/mlt/modules")
set(MLT_DATA_DIR "${BUNDLE_DIR}/Contents/Resources/mlt/data")
if(NOT IS_DIRECTORY "${MLT_MODULE_DIR}" OR NOT IS_DIRECTORY "${MLT_DATA_DIR}")
  message(FATAL_ERROR "MLT runtime directories are missing from the app bundle")
endif()
file(GLOB mlt_modules "${MLT_MODULE_DIR}/*.dylib" "${MLT_MODULE_DIR}/*.so")
file(GLOB mlt_data "${MLT_DATA_DIR}/*")
if(NOT mlt_modules)
  message(FATAL_ERROR "MLT runtime module directory contains no .dylib or .so modules")
endif()
if(NOT mlt_data)
  message(FATAL_ERROR "MLT runtime data directory is empty")
endif()

if(DEFINED DEVELOPMENT_ONLY AND DEVELOPMENT_ONLY)
  if(NOT EXISTS "${BUNDLE_DIR}/Contents/Resources/NOT_FOR_DISTRIBUTION.txt")
    message(FATAL_ERROR "Development bundle is missing its NOT_FOR_DISTRIBUTION marker")
  endif()
endif()
list(LENGTH mlt_modules module_count)
list(LENGTH mlt_data data_count)
message(STATUS "macOS bundle runtime resources: ${module_count} modules, ${data_count} data entries")
