pragma Singleton
import QtQuick

QtObject {
    readonly property color deepest: "#0a0a0a"
    readonly property color background: "#0e0e0e"
    readonly property color panel: "#1a1a1a"
    readonly property color panelRaised: "#1e1e1e"
    readonly property color hover: "#252525"
    readonly property color active: "#2a2a2a"
    readonly property color input: "#141414"
    readonly property color inputActive: "#181818"
    readonly property color divider: "#262626"
    readonly property color border: "#303030"
    readonly property color focusBorder: "#444444"
    readonly property color textPrimary: "#d0d0d0"
    readonly property color textSecondary: "#888888"
    readonly property color textTertiary: "#5e5e5e"
    readonly property color textDisabled: "#424242"
    readonly property color accent: "#ff6e00"
    readonly property color accentHover: "#ff8533"
    readonly property color accentPressed: "#e06200"
    readonly property color accentSoft: "#1aff6e00"
    readonly property color success: "#5cb85c"
    readonly property color error: "#d9534f"
    readonly property color warning: "#f0ad4e"
    readonly property color selection: "#5a321b"
    readonly property color videoClip: "#2c86ad"
    readonly property color audioClip: "#8bbf91"
    readonly property color playhead: "#f04f4f"
}
