#include <cassert>
#include <filesystem>
#include <fstream>
#include <string>

static std::string read(const std::filesystem::path& path) {
  std::ifstream stream(path);
  return {std::istreambuf_iterator<char>(stream), std::istreambuf_iterator<char>()};
}

int main() {
  const std::filesystem::path root = EDWARD_DESKTOP_QML_DIR;
  const auto workbench = read(root / "Workbench.qml");
  const auto tokens = read(root / "DesignTokens.qml");
  const auto main = read(std::filesystem::path(EDWARD_DESKTOP_SOURCE_DIR) / "main.cpp");
  const auto desktopCmake = read(std::filesystem::path(EDWARD_DESKTOP_SOURCE_DIR).parent_path() / "CMakeLists.txt");
  assert(workbench.find("EdwardPreview") == std::string::npos);
  assert(workbench.find("EdwardTimeline") == std::string::npos);
  assert(desktopCmake.find("qml/EdwardPreview.qml") == std::string::npos);
  assert(desktopCmake.find("qml/EdwardTimeline.qml") == std::string::npos);
  assert(workbench.find("generateComponentDraft") != std::string::npos);
  assert(workbench.find("analyzeCurrentClipWithAi") != std::string::npos);
  assert(workbench.find("aiProviderName") != std::string::npos);
  assert(workbench.find("从预设选择供应商") != std::string::npos);
  assert(workbench.find("Chat Completions") != std::string::npos);
  assert(workbench.find("测试模型") != std::string::npos);
  assert(workbench.find("获取模型列表") != std::string::npos);
  assert(workbench.find("aiAvailableModels") != std::string::npos);
  assert(workbench.find("aiModelCredentialsConfigured") != std::string::npos);
  assert(workbench.find("aiModelSelector") != std::string::npos);
  assert(workbench.find("id: aiSettingsDialog") != std::string::npos);
  assert(workbench.find("color: DesignTokens.panel") != std::string::npos);
  assert(workbench.find("text: \"取消\"") != std::string::npos);
  assert(workbench.find("text: \"保存\"") != std::string::npos);
  assert(workbench.find("height: 22") != std::string::npos);
  assert(workbench.find("enabled: !workbenchRuntime.aiModelListBusy") != std::string::npos);
  assert(workbench.find("aiAnalysisDraftAvailable") != std::string::npos);
  assert(workbench.find("applyAiAnalysisDraftToResolve") != std::string::npos);
  assert(workbench.find("aiConversation") != std::string::npos);
  assert(workbench.find("function sendAiDockMessage()") != std::string::npos);
  assert(workbench.find("objectName: \"aiSendButton\"") != std::string::npos);
  assert(workbench.find("Keys.onReturnPressed") != std::string::npos);
  assert(workbench.find("Keys.onEnterPressed") != std::string::npos);
  assert(workbench.find("demoOverlayX") != std::string::npos);
  assert(workbench.find("bindComponentToSelectedClip") != std::string::npos);
  assert(workbench.find("addCurrentComponentToTimeline") != std::string::npos);
  assert(workbench.find("selectedComponentNodeRotation") != std::string::npos);
  assert(workbench.find("selectedComponentNodeScale") != std::string::npos);
  assert(workbench.find("selectedComponentNodeOpacity") != std::string::npos);
  assert(workbench.find("text: \"选中节点缩放: \" + workbenchRuntime.selectedComponentNodeScale") != std::string::npos);
  assert(workbench.find("ensureResolveSubtitleTrack") != std::string::npos);
  assert(workbench.find("导入 Resolve 布局预设") != std::string::npos);
  assert(workbench.find("保存 Edward 侧栏布局") != std::string::npos);
  assert(workbench.find("加载 Edward 侧栏布局") != std::string::npos);
  assert(workbench.find("导出 Edward 侧栏布局") != std::string::npos);
  assert(workbench.find("导入组件草稿") != std::string::npos);
  assert(workbench.find("loadComponentJson") != std::string::npos);
  assert(workbench.find("saveComponentJson") != std::string::npos);
  assert(workbench.find("loadComponentFile") != std::string::npos);
  assert(workbench.find("保存组件 JSON") != std::string::npos);
  assert(workbench.find("保存组件包") != std::string::npos);
  assert(workbench.find("saveComponentPackage") != std::string::npos);
  assert(workbench.find("saveCurrentComponentToLibrary") != std::string::npos);
  assert(workbench.find("保存到我的组件库") != std::string::npos);
  assert(workbench.find("我的组件") != std::string::npos);
  assert(workbench.find("loadLibraryComponent") != std::string::npos);
  assert(workbench.find("saveProject") != std::string::npos);
  assert(workbench.find("loadProject") != std::string::npos);
  assert(workbench.find("hasProjectRecovery") != std::string::npos);
  assert(workbench.find("发现自动保存副本") != std::string::npos);
  assert(workbench.find("恢复自动保存") != std::string::npos);
  assert(workbench.find("if (workbenchRuntime.recoverProject") != std::string::npos);
  assert(workbench.find("title: \"导出\"") != std::string::npos);
  assert(workbench.find("exportDialogRequested") != std::string::npos);
  assert(workbench.find("timelineExportPanel.open()") != std::string::npos);
  assert(workbench.find("exportTimeline") != std::string::npos);
  assert(workbench.find("id: timelineExportPanel") != std::string::npos);
  assert(workbench.find("exportTimelineWithOptions") != std::string::npos);
  assert(workbench.find("选择文件夹") != std::string::npos);
  assert(workbench.find("4K · 3840 × 2160") != std::string::npos);
  assert(workbench.find("[\"24 fps\", \"25 fps\", \"30 fps\", \"50 fps\", \"60 fps\"]") != std::string::npos);
  assert(workbench.find("var frameRates = [24, 25, 30, 50, 60]") != std::string::npos);
  assert(workbench.find("function localPathFromDialogUrl(value)") != std::string::npos);
  assert(workbench.find("window.localPathFromDialogUrl(selectedFolder)") != std::string::npos);
  assert(workbench.find("workbenchRuntime.setPendingFablecutExportPath(outputPath)") != std::string::npos);
  assert(workbench.find("fablecutView.runJavaScript(\"startChosenExport()\")") != std::string::npos);
  assert(workbench.find("fablecutQtOutputSpec") != std::string::npos);
  assert(workbench.find("MP4（H.264）") != std::string::npos);
  assert(workbench.find("timelineExportProgress") != std::string::npos);
  assert(workbench.find("正在导出：") != std::string::npos);
  assert(workbench.find("cancelTimelineExport") != std::string::npos);
  assert(workbench.find("signInWithSupabase") != std::string::npos);
  assert(workbench.find("authenticatedUsername") != std::string::npos);
  assert(workbench.find("上传组件包") != std::string::npos);
  assert(workbench.find("uploadCurrentComponent") != std::string::npos);
  assert(workbench.find("failureTimer") != std::string::npos);
  assert(workbench.find("successTimer") != std::string::npos);
  assert(workbench.find("从文件导入组件") != std::string::npos);
  assert(workbench.find("ApplicationWindow") != std::string::npos);
  assert(workbench.find("objectName: \"sidecarAccountButton\"") != std::string::npos);
  assert(workbench.find("objectName: \"sidecarSettingsButton\"") != std::string::npos);
  assert(workbench.find("id: sidecarScroller") != std::string::npos);
  assert(workbench.find("contentHeight: sidecarContent.height + 32") != std::string::npos);
  assert(workbench.find("id: aiConversationDock") != std::string::npos);
  assert(workbench.find("id: railPageOverlay") != std::string::npos);
  assert(workbench.find("visible: window.activeRailIndex > 0") != std::string::npos);
  assert(workbench.find("visible: window.activeRailIndex === 0") != std::string::npos);
  assert(workbench.find("visible: window.activeRailIndex >= 4") != std::string::npos);
  assert(workbench.find("workbenchRuntime.insertLibraryComponentAtPlayhead(modelData.resourceId)") != std::string::npos);
  assert(main.find("qrc:/qml/Workbench.qml") != std::string::npos);
  assert(main.find("Qt::WindowStaysOnTopHint") != std::string::npos);
  assert(main.find("kReferenceSidebarWidth = 388.0") != std::string::npos);
  assert(main.find("kReferenceScreenWidth = 2560.0") != std::string::npos);
  assert(main.find("qRound(area.width() * kReferenceSidebarWidth / kReferenceScreenWidth)") != std::string::npos);
  assert(workbench.find("qrc:/qml/icons/ai.svg") != std::string::npos);
  assert(workbench.find("qrc:/qml/icons/settings.svg") != std::string::npos);
  assert(workbench.find("property int activeRailIndex: 0") != std::string::npos);
  assert(workbench.find("property int sidebarControlWidth: 340") != std::string::npos);
  assert(workbench.find("visible: window.activeRailIndex > 0") != std::string::npos);
  assert(workbench.find("property var railItems") != std::string::npos);
  assert(workbench.find("property string activeRailLabel") != std::string::npos);
  assert(workbench.find("property int activeInspectorTab: 0") != std::string::npos);
  assert(workbench.find("property int resourceTabIndex: 0") != std::string::npos);
  assert(workbench.find("property bool transformExpanded: true") != std::string::npos);
  assert(workbench.find("property bool effectsExpanded: true") != std::string::npos);
  assert(workbench.find("property bool infoExpanded: true") != std::string::npos);
  assert(workbench.find("property var inspectorTabs") != std::string::npos);
  assert(workbench.find("window.activeInspectorTab = index") != std::string::npos);
  assert(workbench.find("window.resourceTabIndex = index") != std::string::npos);
  assert(workbench.find("window.transformExpanded = !window.transformExpanded") != std::string::npos);
  assert(workbench.find("window.effectsExpanded = !window.effectsExpanded") != std::string::npos);
  assert(workbench.find("window.infoExpanded = !window.infoExpanded") != std::string::npos);
  assert(workbench.find("width: 27; height: 13; radius: 7") != std::string::npos);
  assert(workbench.find("text: window.transformExpanded ? \"⌄\" : \"›\"") != std::string::npos);
  assert(workbench.find("width: 34; height: 30") != std::string::npos);
  assert(workbench.find("text: \"设置\"") != std::string::npos);
  assert(workbench.find("qrc:/qml/icons/microphone.svg") != std::string::npos);
  assert(workbench.find("qrc:/qml/icons/send.svg") != std::string::npos);
  assert(workbench.find("qrc:/qml/icons/plus.svg") != std::string::npos);
  assert(workbench.find("if (activeInspectorTab === 1) return false") != std::string::npos);
  assert(workbench.find("activeInspectorTab === 2") != std::string::npos);
  assert(workbench.find("activeInspectorTab === 3") != std::string::npos);
  assert(workbench.find("function componentSelectionActive()") != std::string::npos);
  assert(workbench.find("function selectionPropertyHint()") != std::string::npos);
  assert(workbench.find("function activeResourceCount()") != std::string::npos);
  assert(workbench.find("function activeTimelineClips()") != std::string::npos);
  assert(workbench.find("workbenchRuntime.selectClip(modelData.id)") != std::string::npos);
  assert(workbench.find("text: window.activeRailLabel + \"资源：\" + window.activeResourceCount()") != std::string::npos);
  assert(workbench.find("组件属性：Edward 控制") != std::string::npos);
  assert(workbench.find("视频片段属性：请在 Resolve 原生 Inspector 调整") != std::string::npos);
  assert(workbench.find("workbenchRuntime.resolveSelectionKind === \"component\"") != std::string::npos);
  assert(workbench.find("text: window.activeRailLabel") != std::string::npos);
  assert(workbench.find("model: window.railItems") != std::string::npos);
  assert(workbench.find("window.activeRailIndex = index") != std::string::npos);
  assert(workbench.find("window.activeUtility = \"\"") != std::string::npos);
  assert(workbench.find("window.activeInspectorTab = 0") != std::string::npos);
  assert(workbench.find("qrc:/qml/video-editor-logo-indigo-pink.png") != std::string::npos);
  assert(workbench.find("sourceSize.width: 1024") != std::string::npos);
  assert(workbench.find("id: aiModelListMouse") != std::string::npos);
  assert(workbench.find("id: aiFooterModelSelector") != std::string::npos);
  assert(workbench.find("window.aiModelEntries().length * 25 + 2") != std::string::npos);
  assert(workbench.find("popup: Popup {") != std::string::npos);
  assert(workbench.find("text: modelData") != std::string::npos);
  assert(workbench.find("radius: 6") != std::string::npos);
  assert(workbench.find("sourceSize.width: 24") != std::string::npos);
  assert(workbench.find("rotation: -45") != std::string::npos);
  assert(workbench.find("id: chatMessagesFlickable") != std::string::npos);
  assert(workbench.find("正在处理") != std::string::npos);
  assert(workbench.find("aiProcessingTimer") != std::string::npos);
  assert(workbench.find("horizontalAlignment: Text.AlignLeft") != std::string::npos);
  assert(workbench.find("ai/conversation") == std::string::npos);
  assert(workbench.find("workbenchRuntime.appendAiConversationError(message)") != std::string::npos);
  assert(workbench.find("Layout.preferredWidth: 135; Layout.preferredHeight: 26") != std::string::npos);
  assert(workbench.find("Layout.preferredWidth: 32") != std::string::npos);
  assert(workbench.find("Layout.preferredHeight: 32") != std::string::npos);
  assert(workbench.find("anchors.centerIn: parent") != std::string::npos);
  assert(tokens.find("#ff6e00") != std::string::npos);
  assert(tokens.find("#0e0e0e") != std::string::npos);
  assert(tokens.find("#1a1a1a") != std::string::npos);
  assert(tokens.find("#d0d0d0") != std::string::npos);
  assert(workbench.find("qrc:/qml/video-editor-logo-indigo-pink.png", workbench.find("qrc:/qml/video-editor-logo-indigo-pink.png") + 1) == std::string::npos);
  assert(workbench.find("Edward · 剪刀手") == std::string::npos);
  assert(workbench.find("text: workbenchRuntime.resolveConnected ? \"刷新 Resolve 上下文\" : \"连接 Resolve Studio\"") == std::string::npos);
  assert(workbench.find("width: window.width / Math.max(window.uiScale, 0.001)") == std::string::npos);
  assert(workbench.find("height: window.height / Math.max(window.uiScale, 0.001)") != std::string::npos);
  assert(workbench.find("xScale: window.uiScale") != std::string::npos);
  assert(workbench.find("property real uiScale: width / 388.0") != std::string::npos);
  assert(workbench.find("maximumWidth: 1") == std::string::npos);
  assert(workbench.find("function uiFontSize(baseSize)") != std::string::npos);
  assert(workbench.find("baseSize + (uiScale < 1.0 ? 1 : 0)") != std::string::npos);
  assert(workbench.find("height: 44") != std::string::npos);
  assert(workbench.find("width: 17; height: 17") != std::string::npos);
  assert(workbench.find("font.pixelSize: window.uiFontSize(9)") != std::string::npos);
  assert(workbench.find("source: \"qrc:/qml/icons/settings.svg\"") != std::string::npos);
  assert(workbench.find("当前对象：") != std::string::npos);
  assert(workbench.find("action: \"fade-in\"") != std::string::npos);
  assert(workbench.find("width: 2") != std::string::npos);
  assert(workbench.find("anchors.topMargin: parent.height * 0.05") != std::string::npos);
  assert(workbench.find("anchors.bottomMargin: parent.height * 0.05") != std::string::npos);
  assert(workbench.find("color: index === window.activeRailIndex ? DesignTokens.accent") != std::string::npos);
  assert(workbench.find("hoverEnabled: true") != std::string::npos);
  assert(main.find("window->setGeometry(area.right() - sidebarWidth + 1") != std::string::npos);
  assert(main.find("Qt::FramelessWindowHint") != std::string::npos);
  assert(main.find("window->setMinimumHeight(area.height())") != std::string::npos);
  assert(main.find("window->setMaximumHeight(area.height())") != std::string::npos);
  assert(workbench.find("title: workbenchRuntime.projectWindowTitle") != std::string::npos);
  assert(workbench.find("id: previewStorageDialog") != std::string::npos);
  assert(workbench.find("configurePreviewStorageRoots") != std::string::npos);
  assert(workbench.find("clearDerivedStorage") != std::string::npos);
  return 0;
}
